# permissions for end users to view storagelocations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: storagelocations-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: demo
    app.kubernetes.io/part-of: demo
    app.kubernetes.io/managed-by: kustomize
  name: storagelocations-viewer-role
rules:
- apiGroups:
  - boxroom.io
  resources:
  - storagelocations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - boxroom.io
  resources:
  - storagelocations/status
  verbs:
  - get
