apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 10b18e697edbf0db733844fc3499323b0a62cc2dca348ca2e04ed8b79bc58eac
    cni.projectcalico.org/podIP: 10.244.96.66/32
    cni.projectcalico.org/podIPs: 10.244.96.66/32
  creationTimestamp: "2023-09-19T12:27:24Z"
  generateName: nginx-deploy-585449566-
  labels:
    app: nginx
    pod-template-hash: "585449566"
  name: nginx-deploy-585449566-mnvh8
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: nginx-deploy-585449566
    uid: 1bd5cd15-8b55-4b74-a19f-4cc170056e54
  resourceVersion: "338979"
  uid: 99508140-85bc-46a3-8aba-8257764c9966
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-fd8tj
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: centos8-db
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-fd8tj
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-09-19T12:27:24Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-09-21T12:07:07Z"
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-09-19T12:27:57Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-09-19T12:27:24Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://3c18d81130f78470574330278f46ef98edfbf717bd21b13365bdb51d7bc7ab54
    image: nginx:latest
    imageID: docker-pullable://nginx@sha256:0d17b565c37bcbd895e9d92315a05c1c3c9a29f762b011a10c54a66cd53c9b31
    lastState: {}
    name: nginx
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-09-19T12:27:56Z"
  hostIP: 10.211.55.7
  phase: Running
  podIP: 10.244.96.66
  podIPs:
  - ip: 10.244.96.66
  qosClass: BestEffort
  startTime: "2023-09-19T12:27:24Z"
